name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_ADMINS: ${{ secrets.BOT_ADMINS }}
        CBR_URL: ${{ vars.CBR_URL }}
      run: python3 -m unittest
